/**
 *  DDL used only for Derby. The order of the table creation is important.  
 */
CREATE TABLE OAUTH_CLIENT_DETAILS (
	CLIENT_ID                VARCHAR(255)  NOT NULL PRIMARY KEY,
	CLIENT_SECRET            VARCHAR(255)  NOT NULL,
	RESOURCE_IDS             VARCHAR(255)  DEFAULT NULL,
	SCOPE                    VARCHAR(255)  DEFAULT NULL,
	AUTHORIZED_GRANT_TYPES   VARCHAR(255)  DEFAULT NULL,
	WEB_SERVER_REDIRECT_URI  VARCHAR(255)  DEFAULT NULL,
	AUTHORITIES              VARCHAR(255)  DEFAULT NULL,
	ACCESS_TOKEN_VALIDITY    INT           DEFAULT NULL,
	REFRESH_TOKEN_VALIDITY   INT           DEFAULT NULL,
	ADDITIONAL_INFORMATION   VARCHAR(4096) DEFAULT NULL,
	AUTOAPPROVE              VARCHAR(255)  DEFAULT NULL);

CREATE TABLE PERMISSION (
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NAME VARCHAR(60) UNIQUE);

CREATE TABLE ROLE (ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
NAME VARCHAR(60) UNIQUE);

CREATE TABLE PERMISSION_ROLE(
    PERMISSION_ID INT,
    FOREIGN KEY(PERMISSION_ID) REFERENCES PERMISSION(ID),
    ROLE_ID INT,
    FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID));
    
 CREATE TABLE APPUSER(
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USERNAME            VARCHAR(24)  UNIQUE NOT NULL,
    PASSWORD            VARCHAR(255) NOT NULL,
    EMAIL               VARCHAR(255) NOT NULL,
    ENABLED             SMALLINT     NOT NULL,
    ACCOUNT_EXPIRED     SMALLINT     NOT NULL,
    CREDENTIALS_EXPIRED SMALLINT     NOT NULL,
    ACCOUNT_LOCKED      SMALLINT     NOT NULL);   
 
 CREATE TABLE ROLE_USER (ROLE_ID INT,FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID),
    USER_ID INT, FOREIGN KEY(USER_ID) REFERENCES APPUSER(ID));